# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'przywitanie(1).ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3
import time

class Ui_Youbook(object):
    def setupUi(self, Youbook):
        Youbook.setObjectName("Youbook")
        Youbook.resize(784, 598)
        Youbook.setMinimumSize(QtCore.QSize(784, 598))
        Youbook.setMaximumSize(QtCore.QSize(784, 598))
        Youbook.setSizeIncrement(QtCore.QSize(5, 2))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        Youbook.setFont(font)
        Youbook.setStyleSheet("background-color: rgb(248, 120, 120);\n"
"selection-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Youbook)
        self.centralwidget.setObjectName("centralwidget")
        self.jakiuzytkownik = QtWidgets.QLabel(self.centralwidget)
        self.jakiuzytkownik.setGeometry(QtCore.QRect(580, 0, 191, 41))
        self.jakiuzytkownik.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.01 rgba(255, 112, 112, 255), stop:1 rgba(255, 255, 255, 255));")
        self.jakiuzytkownik.setObjectName("jakiuzytkownik")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 500, 761, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(362, 16777215))
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.01 rgba(255, 112, 112, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setSizeIncrement(QtCore.QSize(0, 3))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.01 rgba(255, 112, 112, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 761, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.01 rgba(255, 112, 112, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 180, 761, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 741, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        Youbook.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Youbook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 21))
        self.menubar.setObjectName("menubar")
        self.menuWype_nij_formularz = QtWidgets.QMenu(self.menubar)
        self.menuWype_nij_formularz.setObjectName("menuWype_nij_formularz")
        self.menuFormularz = QtWidgets.QMenu(self.menuWype_nij_formularz)
        self.menuFormularz.setObjectName("menuFormularz")
        Youbook.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Youbook)
        self.statusbar.setObjectName("statusbar")
        Youbook.setStatusBar(self.statusbar)
        self.Twojalista = QtWidgets.QAction(Youbook)
        self.Twojalista.setObjectName("Twojalista")
        self.Wyloguj = QtWidgets.QAction(Youbook)
        self.Wyloguj.setObjectName("Wyloguj")
        self.Nowy = QtWidgets.QAction(Youbook)
        self.Nowy.setObjectName("Nowy")
        self.Popraw = QtWidgets.QAction(Youbook)
        self.Popraw.setObjectName("Popraw")
        self.Zamknij = QtWidgets.QAction(Youbook)
        self.Zamknij.setObjectName("Zamknij")
        self.menuFormularz.addAction(self.Nowy)
        self.menuFormularz.addAction(self.Popraw)
        self.menuWype_nij_formularz.addAction(self.menuFormularz.menuAction())
        self.menuWype_nij_formularz.addAction(self.Twojalista)
        self.menuWype_nij_formularz.addSeparator()
        self.menuWype_nij_formularz.addAction(self.Wyloguj)
        self.menuWype_nij_formularz.addAction(self.Zamknij)
        self.menubar.addAction(self.menuWype_nij_formularz.menuAction())

        self.retranslateUi(Youbook)
        QtCore.QMetaObject.connectSlotsByName(Youbook)

    def retranslateUi(self, Youbook):
        _translate = QtCore.QCoreApplication.translate
        Youbook.setWindowTitle(_translate("Youbook", "BOOK&YOU"))

        #####################################################################################
        time.sleep(1)
        con = sqlite3.connect("login.db")
        zalogowany = con.execute('SELECT * FROM USERS WHERE ZALOGOWANY=1')
        for osoba in zalogowany:
            print(osoba[0])
            użytkownik = osoba[0]
        con.commit()
        con.close()
        nazwa_użytkownika = "Użytkownik : " + str(użytkownik)

        self.jakiuzytkownik.setText(_translate("Youbook", nazwa_użytkownika))
        self.pushButton_2.setText(_translate("Youbook", "Nowy Formularz"))
        self.pushButton.setText(_translate("Youbook", "Moja lista"))
        self.label.setText(_translate("Youbook", "Witaj ! BOOK&YOU to aplikacja, która pomoże Ci znaleźć książki napisane specjalnie dla Ciebie!"))
        self.label_3.setText(_translate("Youbook", "Instrucja obsługi !"))
        self.label_4.setText(_translate("Youbook", "TextLabel"))
        self.label_5.setText(_translate("Youbook", "TextLabel"))
        self.label_6.setText(_translate("Youbook", "TextLabel"))
        self.label_2.setText(_translate("Youbook", "TextLabel"))
        self.menuWype_nij_formularz.setTitle(_translate("Youbook", "Menu"))
        self.menuFormularz.setTitle(_translate("Youbook", "Fomularz"))
        self.Twojalista.setText(_translate("Youbook", "Twoja lista"))
        self.Wyloguj.setText(_translate("Youbook", "Wyloguj"))
        self.Nowy.setText(_translate("Youbook", "Nowy formularz"))
        self.Popraw.setText(_translate("Youbook", "Popraw swój formularz"))
        self.Zamknij.setText(_translate("Youbook", "Zamknij"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Youbook = QtWidgets.QMainWindow()
    ui = Ui_Youbook()
    ui.setupUi(Youbook)
    Youbook.show()
    sys.exit(app.exec_())

